version: '3.8'

services:
  web-app:
    image: quanpham12/javapro:latest
    container_name: phamxuanminhquan-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/product_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword

  db:
    image: mysql:8.0
    container_name: phamxuanminhquan-db
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=product_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
